DROP USER brightway_admin CASCADE;

-- Create Brightway admin user
CREATE USER brightway_admin IDENTIFIED BY "BRIGHTWAY_ADMIN"
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    QUOTA UNLIMITED ON users;

GRANT "CONNECT" TO brightway_admin ;

-- QUOTAS
ALTER USER brightway_admin QUOTA UNLIMITED ON "USERS";

-- ROLES
ALTER USER brightway_admin DEFAULT ROLE "CONNECT";

GRANT READ ANY TABLE TO "BRIGHTWAY_ADMIN";
GRANT SELECT ANY DICTIONARY TO "BRIGHTWAY_ADMIN";
GRANT EXECUTE ANY OPERATOR TO "BRIGHTWAY_ADMIN";
GRANT DROP ANY OPERATOR TO "BRIGHTWAY_ADMIN";
GRANT ALTER ANY OPERATOR TO "BRIGHTWAY_ADMIN";
GRANT CREATE ANY OPERATOR TO "BRIGHTWAY_ADMIN";
GRANT CREATE OPERATOR TO "BRIGHTWAY_ADMIN";
GRANT DROP ANY TYPE TO "BRIGHTWAY_ADMIN";
GRANT ALTER ANY TYPE TO "BRIGHTWAY_ADMIN";
GRANT CREATE ANY TYPE TO "BRIGHTWAY_ADMIN";
GRANT CREATE TYPE TO "BRIGHTWAY_ADMIN";
GRANT DROP ANY TRIGGER TO "BRIGHTWAY_ADMIN";
GRANT ALTER ANY TRIGGER TO "BRIGHTWAY_ADMIN";
GRANT CREATE ANY TRIGGER TO "BRIGHTWAY_ADMIN";
GRANT CREATE TRIGGER TO "BRIGHTWAY_ADMIN";
GRANT EXECUTE ANY PROCEDURE TO "BRIGHTWAY_ADMIN";
GRANT DROP ANY PROCEDURE TO "BRIGHTWAY_ADMIN";
GRANT ALTER ANY PROCEDURE TO "BRIGHTWAY_ADMIN";
GRANT CREATE ANY PROCEDURE TO "BRIGHTWAY_ADMIN";
GRANT CREATE PROCEDURE TO "BRIGHTWAY_ADMIN";
GRANT DROP ANY SEQUENCE TO "BRIGHTWAY_ADMIN";
GRANT ALTER ANY SEQUENCE TO "BRIGHTWAY_ADMIN";
GRANT CREATE ANY SEQUENCE TO "BRIGHTWAY_ADMIN";
GRANT CREATE SEQUENCE TO "BRIGHTWAY_ADMIN";
GRANT DROP ANY VIEW TO "BRIGHTWAY_ADMIN";
GRANT CREATE ANY VIEW TO "BRIGHTWAY_ADMIN";
GRANT CREATE VIEW TO "BRIGHTWAY_ADMIN";
GRANT DROP ANY SYNONYM TO "BRIGHTWAY_ADMIN";
GRANT CREATE ANY SYNONYM TO "BRIGHTWAY_ADMIN";
GRANT CREATE SYNONYM TO "BRIGHTWAY_ADMIN";
GRANT DROP ANY INDEX TO "BRIGHTWAY_ADMIN";
GRANT ALTER ANY INDEX TO "BRIGHTWAY_ADMIN";
GRANT CREATE ANY INDEX TO "BRIGHTWAY_ADMIN";
GRANT UPDATE ANY TABLE TO "BRIGHTWAY_ADMIN";
GRANT INSERT ANY TABLE TO "BRIGHTWAY_ADMIN";
GRANT SELECT ANY TABLE TO "BRIGHTWAY_ADMIN";
GRANT DROP ANY TABLE TO "BRIGHTWAY_ADMIN";
GRANT ALTER ANY TABLE TO "BRIGHTWAY_ADMIN";
GRANT CREATE ANY TABLE TO "BRIGHTWAY_ADMIN";
GRANT CREATE TABLE TO "BRIGHTWAY_ADMIN";
GRANT CREATE USER TO "BRIGHTWAY_ADMIN";
GRANT UNLIMITED TABLESPACE TO "BRIGHTWAY_ADMIN";
GRANT DROP TABLESPACE TO "BRIGHTWAY_ADMIN";
GRANT ALTER TABLESPACE TO "BRIGHTWAY_ADMIN";
GRANT CREATE TABLESPACE TO "BRIGHTWAY_ADMIN";
GRANT CREATE SESSION TO "BRIGHTWAY_ADMIN";

commit;
/